// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRBfrd-0CC5eufZiFmanq5bgwwQPNF9jA',
    appId: '1:657794193629:web:9b6ca6266d6ee0dcf06334',
    messagingSenderId: '657794193629',
    projectId: 'ecommerceapplication-a2e7c',
    authDomain: 'ecommerceapplication-a2e7c.firebaseapp.com',
    storageBucket: 'ecommerceapplication-a2e7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ZTBfBQr1iqJ8vZRVwZJaFR-HMasgxtA',
    appId: '1:657794193629:android:dc573d19cc8d3b91f06334',
    messagingSenderId: '657794193629',
    projectId: 'ecommerceapplication-a2e7c',
    storageBucket: 'ecommerceapplication-a2e7c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNMmmSRtrVl9G9ZTiePJ-I5HAl24qn_ac',
    appId: '1:657794193629:ios:794dcbe7b8eccf0af06334',
    messagingSenderId: '657794193629',
    projectId: 'ecommerceapplication-a2e7c',
    storageBucket: 'ecommerceapplication-a2e7c.firebasestorage.app',
    androidClientId: '657794193629-963ig2ssap4u9v7mbfv4i4abs217i2tq.apps.googleusercontent.com',
    iosClientId: '657794193629-a964jd606tp8q51t4tl5ibn1rjj7h877.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRBfrd-0CC5eufZiFmanq5bgwwQPNF9jA',
    appId: '1:657794193629:web:93bb66fbb082db83f06334',
    messagingSenderId: '657794193629',
    projectId: 'ecommerceapplication-a2e7c',
    authDomain: 'ecommerceapplication-a2e7c.firebaseapp.com',
    storageBucket: 'ecommerceapplication-a2e7c.firebasestorage.app',
  );
}
